SDK-1331 - web3_clientVersion should return EON version
HorizenOfficial/Sidechains-SDK pull request #1005
Opened 2024-03-18 09:18 UTC by i-skrypnyk

https://horizenlabs.atlassian.net/browse/SDK-1331
Simple change to include eon version into web3_clientVersion response instead of sdk version

2024-03-18 10:22 UTC, saratnt requested changes
LGTM.
Just sc_evm_rpc_web3_methods.py test should be updated too.

2024-03-19 15:44 UTC, paolocappelletti approved these changes

2024-03-20 15:38 UTC, saratnt approved these changes

2024-03-21 10:46 UTC, alsala approved these changes

2024-03-21 14:58 UTC, merged