Added new fork for EON 1.5 disabling of backward transfers
HorizenOfficial/Sidechains-SDK pull request #1051
Opened 2024-07-02 16:01 UTC by alsala

Introduce a EON 1.5 hardfork that will disable backward transfer requests to the mainchain 

https://horizenlabs.atlassian.net/browse/EON-1913

2024-07-03 08:31 UTC, saratnt requested changes
LGTM, just 2 really minor comments

2024-07-03 08:31 UTC, saratnt commented on qa/sc_evm_backward_transfer.py
> +            fail("Interoperability call should fail before fork point")
The fail message is not correct, it should fail because after fork 1.5 the backward transfer is disabled.

2024-07-03 08:31 UTC, saratnt commented on qa/sc_evm_backward_transfer.py
> +            # error is raised from API since the address has no balance
This comment should be removed

2024-07-05 09:08 UTC, paolocappelletti approved these changes

2024-07-05 09:09 UTC, saratnt approved these changes

2024-07-05 09:14 UTC, merged