Sending certificate to MC via websocket.
HorizenOfficial/Sidechains-SDK pull request #201
Opened 2020-09-18 17:08 UTC by VolodymyrBabaiev

2020-09-22 07:30 UTC, i-Alex requested changes

2020-09-22 12:09 UTC, i-Alex submitted a review, later dismissed

2020-10-09 07:00 UTC, i-Alex approved these changes

2020-10-09 10:13 UTC, albertog78 approved these changes

2020-10-09 10:13 UTC, albertog78 commented on sdk/src/main/scala/com/horizen/websocket/MainchainNodeChannelImpl.scala
> +    val backwardTransfer:Seq[BackwardTransfer] = certificateRequest.backwardTransfers.map(bt => BackwardTransfer(BytesUtils.toHexString(bt.pubkeyhash), bt.amount))
val backwardTransfer*s*

2020-10-15 09:43 UTC, merged