Added get headers websocket request.
HorizenOfficial/Sidechains-SDK pull request #221
Opened 2020-10-27 10:33 UTC by VolodymyrBabaiev

In order to improve performance(SC ceased when it more than 50 blocks beyond MC, in order to forge block SC needs to retrieve 50 block from MC, but fails due to timeout) get_block_headers websocket request was implemented. It allows to retrieve up to 50 block headers from MC in one requests.

2020-11-02 07:15 UTC, i-Alex requested changes

2020-12-09 03:48 UTC, VolodymyrBabaiev commented on qa/mc_sc_forging4.py
> +     TODO In tests when SC is more than 50 blocks beyond MC Forger cannot retrieve more than 49 block headers
Correct, SC retrieves 50 header hashes one of them is common one.

2020-12-09 03:51 UTC, butnaka commented
thank you admin

2020-12-09 03:59 UTC, VolodymyrBabaiev commented on sdk/src/main/scala/com/horizen/forge/MainchainSynchronizer.scala
> +    val HEADERS_REQUEST_LIMIT = 25 // TODO Change this value to 50 after changing HEADERS_LIMIT. It has to be 50(as described in doc and implemented in MC)
It's possible to retrieve 50 headers in one request from MC. Limit of headers changed to 25 in order to keep track of correctness of case when getMainchainBlockHeaders makes several header requests to MC. When HEADERS_LIMIT value will be actualized(to maxim possible amount of headers in one block could be included) this value should be changed to 50.

2020-12-09 04:35 UTC, VolodymyrBabaiev commented on sdk/src/main/scala/com/horizen/forge/MainchainSynchronizer.scala
> +      headers ++= mainchainNodeChannel.getBlockHeaders(group).get
If we put exception handling here in some cases calling function could receive only part of requested headers without being notified of cause of the missing headers. In current implementation calling function receives all requested headers or exception in other case.

2020-12-15 10:03 UTC, i-Alex requested changes

2020-12-15 10:03 UTC, i-Alex commented on qa/mc_sc_forging4.py
> +    - Mine 200 MC blocks, then forge SC block, verify MC data inclusion
Let's simplify the test flow:
- Mine 200 MC blocks
- Forger N SC blocks and verify MC block headers  and ref data inclusion.
Keeping in mind max number of 49 MC headers per SC block for now.

Later we will update the test case according to the changes in Forger logic.

2020-12-16 08:25 UTC, i-Alex approved these changes

2021-03-26 09:54 UTC, albertog78 approved these changes

2021-03-29 14:35 UTC, merged