Issue 197 - external testframework support
HorizenOfficial/Sidechains-SDK pull request #244
Opened 2021-03-04 14:35 UTC by paolocappelletti

parametrized a couple of lines in the testframework to let external tests in sidechain applications to run

2021-03-04 15:49 UTC, i-Alex requested changes

2021-03-04 15:49 UTC, i-Alex commented on qa/SidechainTestFramework/scutil.py
> +    if os.path.isfile(customFileName):
fine for now, but we may improve it in the future to be more flexible with custom configs.

2021-03-04 15:49 UTC, i-Alex commented on qa/SidechainTestFramework/scutil.py
> +                               os.getenv("SIDECHAIN_SDK", "..") + "/tools/sctool/target/sidechains-sdk-scbootstrappingtools-0.2.7.jar",
please, update also qa readme file https://github.com/HorizenOfficial/Sidechains-SDK/tree/dev/qa with `SIDECHAIN_SDK` env var.

2021-03-16 10:04 UTC, paolocappelletti commented on qa/SidechainTestFramework/scutil.py
> +                               os.getenv("SIDECHAIN_SDK", "..") + "/tools/sctool/target/sidechains-sdk-scbootstrappingtools-0.2.7.jar",
done

2021-03-16 10:59 UTC, i-Alex approved these changes

2021-03-23 10:30 UTC, albertog78 approved these changes

2021-03-23 10:30 UTC, merged