Certificate submitter optimization[draft]
HorizenOfficial/Sidechains-SDK pull request #261
Opened 2021-05-21 08:23 UTC by VolodymyrBabaiev

…socket request.

2021-05-21 18:02 UTC, MASOUDFOROTAN approved these changes

2021-06-09 08:06 UTC, i-Alex requested changes

2021-06-09 08:06 UTC, i-Alex commented on sdk/src/test/scala/com/horizen/websocket/MainchainNodeChannelImplTest.scala
> +  def getTopQualityCertificates(): Unit = {
Also, we need to extend `sc_multiple_certs.py` test to verify the new logic. To be discussed.

2021-06-15 15:01 UTC, i-Alex requested changes

2021-06-15 15:01 UTC, i-Alex commented on qa/demo.py
> -            time.sleep(10)
let's keep sleep at least for 1 sec.

2021-06-15 15:01 UTC, i-Alex commented on qa/sc_backward_transfer.py
>              time.sleep(10)
can reduce to 1 sec, for example. Same in other places.

2021-06-16 07:24 UTC, VolodymyrBabaiev commented on sdk/src/test/scala/com/horizen/websocket/MainchainNodeChannelImplTest.scala
> +  def getMempoolTopQualityCertificates(): Unit = {
Done.

2021-06-16 12:26 UTC, VolodymyrBabaiev commented on sdk/src/main/scala/com/horizen/websocket/MainchainNodeChannel.scala
> +  // Get information about best certificates in mempool and chain
Done.

2021-06-16 13:06 UTC, i-Alex approved these changes

2021-06-22 09:10 UTC, albertog78 requested changes

2021-06-22 09:10 UTC, albertog78 commented on sdk/src/main/scala/com/horizen/certificatesubmitter/CertificateSubmitter.scala
> +        topQualityCertificates.mempoolCertInfo.quality.getOrElse(topQualityCertificates.chainCertInfo.quality.getOrElse(0))
ignore from block certificates the one not belonging to the expected epoch and assert that the one in the mempool is of the current epoch

2021-06-24 08:29 UTC, i-Alex requested changes
Please, do merge from dev and resolve the conflicts. + update python tests with the case when cert is present in MC mempool and then SC block is generated.

2021-06-24 08:29 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/certificatesubmitter/CertificateSubmitter.scala
> +        if (!topQualityCertificates.mempoolCertInfo.quality.isEmpty) {
I would suggest to add the same condition as for inchain cert: ` && topQualityCertificates.mempoolCertInfo.epoch.get == epoch`

2021-06-24 08:29 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/certificatesubmitter/CertificateSubmitter.scala
> +        ex.printStackTrace()
use `log.info` or `log.debug`

2021-06-25 10:29 UTC, i-Alex approved these changes

2021-07-01 14:33 UTC, albertog78 approved these changes

2021-07-01 14:33 UTC, merged