Box type property
HorizenOfficial/Sidechains-SDK pull request #315
Opened 2021-12-21 08:20 UTC by VolodymyrBabaiev

Added typeName and isCustom JSON box properties.
typeId property has been removed.

2021-12-21 08:27 UTC, i-Alex approved these changes

2021-12-24 15:40 UTC, i-Alex requested changes
Let's add typeName, isCustom methods and remove typeId json from json view for Secret and Transaction types. There we have the same possibility for developers to define custom types with the same typeId.

2022-01-17 12:36 UTC, i-Alex requested changes

2022-01-17 12:36 UTC, i-Alex commented on sdk/src/main/java/com/horizen/secret/Secret.java
> +@JsonIgnoreProperties({"secretTypeId", "publicImage", "serializer", "sign", "owns"})
Let's leave `publicImage` as a part of json view. It is useful to have.

2022-01-17 12:36 UTC, i-Alex commented on sdk/src/main/java/com/horizen/transaction/AbstractRegularTransaction.java
> +    public String typeName() {
these 2 methods can be removed since were defined in `BoxTransaction`.

2022-01-19 19:24 UTC, VolodymyrBabaiev commented on sdk/src/main/resources/api/sidechainApi.yaml
> +        typeName:
Done.

2022-01-20 08:48 UTC, i-Alex approved these changes

2022-01-26 11:00 UTC, albertog78 approved these changes

2022-01-26 11:41 UTC, merged