St/api update
HorizenOfficial/Sidechains-SDK pull request #328
Opened 2022-02-10 16:28 UTC by saratnt

- Added height field in findBlockByID HTTP API
- Added findBlockInfoByID and storageVersions HTTP APIs
- Fix for Issue #326

2022-02-15 15:22 UTC, i-Alex requested changes
Seems good!

2022-02-15 15:22 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/api/http/SidechainBlockApiRoute.scala
> +  private[api] case class RespFindBlockInfoById(block: SidechainBlockInfo, isInActiveChain: Boolean) extends SuccessResponse
block -> blockInfo

2022-02-15 15:22 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/block/SidechainBlock.scala
> +  val BlockIdLenght = 64
BlockIdLeng**ht** -> BlockIdLeng**th**

Moreover, it is the length of the id in a string hex form

2022-02-15 15:22 UTC, i-Alex commented on sdk/src/test/resources/log4j2-test.xml
> +        <!--RollingFile name="errorLog" fileName="log/application2-error.log"
I guess, we can remove the commented part.

2022-02-15 15:22 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/SidechainNodeViewHolder.scala
> +    case class GetStorageVersions()
can be changed to `case object GetStorageVersions` since it doesn't require any parameters.

2022-06-17 09:56 UTC, i-Alex approved these changes

2022-06-17 10:55 UTC, saratnt commented
Approved

2022-06-21 13:04 UTC, merged