Fixed messege priority for Certificate Submitter Actor.
HorizenOfficial/Sidechains-SDK pull request #403
Opened 2022-06-16 10:53 UTC by VolodymyrBabaiev

Reduced message priority for SemanticallySuccessfulModifier. It fixes blocking Certificate Submitter during Node synchronization and fixes messing up Certificate Signatures that were received from remote.

Also introduced ObsoleteWithdrawalEpochException exception to getTopQualityCertificate. It throws this exception when the requested epoch number is lower than the current epoch. It disables certificate generation.

2022-06-21 07:48 UTC, i-skrypnyk approved these changes
Other than minor refactoring, no other points, LGTM.

2022-06-22 09:24 UTC, i-Alex requested changes
When I'm running `sc_cert_submitter_after_sync_2.py` I now constantly see the following message:
`[ERROR] 2022-06-22 12:04:11:347 +0300 [  CertificateSubmitter.scala:427 ] [2-Hop-akka.actor.default-dispatcher-2] com.horizen.certificatesubmitter.CertificateSubmitter - Trying to schedule certificate generation being outside Certificate submission window.`

I this it is expected, but let's double check and see if it is ok to make it as "warn" instead of "error"

2022-06-29 12:22 UTC, VolodymyrBabaiev commented on sdk/src/main/scala/com/horizen/certificatesubmitter/CertificateSubmitter.scala
> +    Props(new CertificateSubmitter(settings, sidechainNodeViewHolderRef, params, mainchainChannel)).withMailbox("akka.actor.deployment.prio-mailbox")
It's not failing at all. Cause problem is pretty tricky I also introduce a couple of Submitter API checks to the python test.

2022-06-29 15:02 UTC, i-Alex approved these changes

2022-06-29 15:03 UTC, merged