WIP: Add logic for wallet required rpc calls
HorizenOfficial/Sidechains-SDK pull request #425
Opened 2022-06-29 08:58 UTC by akrckn

2022-06-30 13:12 UTC, i-Alex requested changes

2022-07-01 08:20 UTC, akrckn commented on sdk/src/test/java/com/horizen/account/api/rpc/service/EthServiceTest.java
> +        assertEquals("0x67D", ((Quantity) ethService.execute(rpcRequest)).getValue());
I already rewrote the test in scala

2022-07-04 07:14 UTC, i-Alex requested changes

2022-07-04 07:14 UTC, i-Alex commented on sdk/src/main/java/com/horizen/account/api/rpc/service/EthService.java
> +        return new Quantity(String.valueOf(getBestBlock().header().id()));
block number expected, not block `id`. get the height from history or state.

2022-07-04 15:09 UTC, merged