Prevent FT to non-EOA account
HorizenOfficial/Sidechains-SDK pull request #487
Opened 2022-08-03 18:15 UTC by JcBernack

- prevent balance changes by forward transfers to non-EOA accounts
- add TODO that we want to return the amount to the mcReturnAddress later
- add python test to verify that a FT to an existing smart contract account will not change the balance

2022-08-05 07:31 UTC, i-Alex requested changes
Looks good. A minor change in the test description required.

2022-08-05 07:31 UTC, i-Alex commented on qa/sc_evm_forward_transfer.py
> +Check an EVM Storage Smart Contract.
Need to update the description here.

2022-08-05 07:31 UTC, i-Alex commented on qa/sc_evm_forward_transfer.py
> +        - Read the different string in a read only call
This can be removed.

2022-08-05 09:34 UTC, alsala approved these changes

2022-08-05 14:07 UTC, JcBernack commented on qa/sc_evm_forward_transfer.py
> +Check an EVM Storage Smart Contract.
done

2022-08-05 14:07 UTC, JcBernack commented on qa/sc_evm_forward_transfer.py
> +        - Read the different string in a read only call
done

2022-08-08 11:53 UTC, i-Alex approved these changes

2022-08-08 11:53 UTC, merged