[SDK-354] Optimized chainAfter method
HorizenOfficial/Sidechains-SDK pull request #523
Opened 2022-09-02 13:40 UTC by MarcoOl94

## Description
Starting from an issue observed during the synchronization of the Explorer:

`scnode | [DEBUG] 2022-08-24 08:21:39:076 +0000 [Grizzly-worker(7)] com.horizen.websocket.server.WebSocketServerEndpoint - Error inside GET_NEW_BLOCK_HASHES websocket request: java. lang.Exception: java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]`

I've discovered that the function **chainAfter** was not optimized and it did scan the entire blockchain from a starting block height to the actual tip.
This means that when the explorer wants to sync the blockchain from scratch, this function iterate from the genesis block to the tip and this was not performed in time (5 seconds) and doesn't scale with the growth of the blockchain.
In order to solve this I've added an additional termination condition inside the function after a certain number of blocks.

## Jira Ticket
[354](https://horizenlabs.atlassian.net/jira/software/c/projects/SDK/boards/14?view=detail&selectedIssue=SDK-354&assignee=615f31c32f6aed0068c67291)

## Changes

- Optimized function **chainAfter**

## Checks
- [✔] Project Builds
- [✔] Project passes unit tests
- [✔] Project passes integration tests (Python)
- [✘] Updated documentation accordingly

2022-09-08 08:58 UTC, i-Alex requested changes
Seems good

2022-09-08 08:59 UTC, paolocappelletti requested changes

2022-09-08 08:59 UTC, paolocappelletti commented on sdk/src/main/scala/com/horizen/chain/ElementsChain.scala
> +      if (height - startHeight +1 <= blockLimit) {
if  (currentHeight == height)

I think should have the same result and is more readable

2022-09-09 07:35 UTC, MarcoOl94 commented on sdk/src/test/scala/com/horizen/integration/SidechainHistoryTest.scala
> +    continuationIds = history1.continuationIds(history1SyncInfo, Int.MaxValue -1)
Agree, i'll add this check.

2022-09-09 15:49 UTC, i-Alex approved these changes

2022-09-09 15:53 UTC, paolocappelletti approved these changes

2022-09-09 15:53 UTC, merged