Circuit with key rotation pytests
HorizenOfficial/Sidechains-SDK pull request #583
Opened 2022-11-01 13:47 UTC by sgonta

2022-11-01 14:43 UTC, i-Alex requested changes

2022-11-01 14:43 UTC, i-Alex commented on qa/test_framework/util.py
> +        fe_certificate_field_configs = certificate_with_key_rotation_field_config
I propose to add more comments, explaining this tricky configs.
And moreover, we may restructure a bit:
```
if type_of_circuit_number == 0:
  assert sc_creation_version <= 1
  fe_certificate_field_configs = ce...

elif type_of_circuit_number == 1:
  assert sc_creation_version == 2
  assert is_csw_enabled is False
  fe_certificate_field_configs = certificate_with_key_rotation_field_config
  
```

2022-11-01 14:43 UTC, i-Alex commented on tools/sctool/src/main/java/com/horizen/ScBootstrappingToolCommandProcessor.java
> +        List<String> mastersPublicKeys = new ArrayList<String>();
check that `mastersPublicKeys` size equals to `signersPublicKeys` and throw proper error.

2022-11-01 14:43 UTC, i-Alex commented on tools/sctool/src/main/java/com/horizen/ScBootstrappingToolCommandProcessor.java
> +        boolean isCSWEnabled = json.get("isCSWEnabled").asBoolean();
can be removed. Not a case for new circuit.

2022-11-01 14:43 UTC, i-Alex commented on tools/sctool/src/main/java/com/horizen/ScBootstrappingToolCommandProcessor.java
> +            }
For new circuit we have another constant with value `1`

2022-11-01 14:43 UTC, i-Alex commented on tools/sctool/src/main/java/com/horizen/ScBootstrappingToolCommandProcessor.java
> +        }
separate them into signersPublicKeys and mastersPublicKeys.
In STF they must be used in different way

2022-11-02 09:23 UTC, MarcoOl94 requested changes

2022-11-02 09:23 UTC, MarcoOl94 commented on qa/SidechainTestFramework/scutil.py
> +        public_master_keys.append(keys.publicKey)
Master public keys should be generated in the same way of the signer keys, they should not be the same.

2022-11-02 09:23 UTC, MarcoOl94 commented on qa/resources/template_predefined_genesis.conf
>      signersThreshold = 5
Add also here the master public keys placeholder

2022-11-10 09:27 UTC, sgonta commented
Changes are merged into mo/key_rotation branch

2022-11-10 09:27 UTC, closed without merging