libevm mega review
HorizenOfficial/Sidechains-SDK pull request #623
Opened 2022-11-25 18:03 UTC by JcBernack

- [ ] [EVM-425](https://horizenlabs.atlassian.net/browse/EVM-425)

2022-12-06 12:35 UTC, akrckn approved these changes

2022-12-07 16:11 UTC, i-Alex requested changes
Looks very good!
A minor point in UTs left.

2022-12-07 16:11 UTC, i-Alex commented on libevm/lib/refund.go
> +func (s *Service) StateGetRefund(params HandleParams) (error, hexutil.Uint64) {
Seeems method is not tested.
At the moment we use statedb method directly in the test: `if refund := statedb.GetRefund(); refund != tt.refund {`
Let's use the new method to test the instance properly.

2022-12-09 16:52 UTC, i-Alex approved these changes

2022-12-09 16:52 UTC, merged