String charset specification.
HorizenOfficial/Sidechains-SDK pull request #660
Opened 2022-12-16 16:55 UTC by VolodymyrBabaiev

Add UTF-8 charset specification for every String.getBytes() invocation.

It's draft pull request because regression tests hasn't been run yet.

2023-01-09 11:45 UTC, alsala requested changes
sdk/src/main/scala/com/horizen/consensus/ConsensusDataProvider.scala:183:    new ByteArrayWrapper(Utils.doubleSHA256HashOfConcatenation(blockId.getBytes, nonceConsensusEpochInfo.consensusNonce))
sdk/src/test/scala/com/horizen/consensus/ConsensusDataStorageTest.scala:48:      val nonExistingId = blockIdToEpochId(bytesToId(Utils.doubleSHA256Hash(id.getBytes())))
sdk/src/test/scala/com/horizen/consensus/ConsensusDataStorageTest.scala:65:      val nonExistingId = blockIdToEpochId(bytesToId(Utils.doubleSHA256Hash(id.getBytes())))
sdk/src/test/scala/com/horizen/consensus/ConsensusDataProviderTest.scala:52:    consensusDataStorage.addStakeConsensusEpochInfo(epochId, StakeConsensusEpochInfo(epochId.getBytes.take(merkleTreeHashLen), (index + 1) * 1000))}
sdk/src/test/scala/com/horizen/consensus/ConsensusDataProviderTest.scala:96:    val newBlockId = bytesToId(Utils.doubleSHA256Hash(parentId.getBytes))
sdk/src/test/scala/com/horizen/consensus/ConsensusDataProviderTest.scala:196:    assertTrue(epochIdsForFirstDataProvider.head.getBytes.take(merkleTreeHashLen).sameElements(consensusInfoForGenesisEpoch.stakeConsensusEpochInfo.rootHash))
sdk/src/test/scala/com/horizen/account/receipt/ReceiptFixture.scala:53:      Keccak256.hash(blockHash.getBytes).asInstanceOf[Array[Byte]],
sdk/src/test/java/com/horizen/utils/ListSerializerTest.java:56:        writer.putBytes(obj._testData.getBytes());

2023-01-10 11:17 UTC, davehorizen approved these changes

2023-01-19 13:23 UTC, i-Alex approved these changes

2023-01-19 13:44 UTC, davehorizen approved these changes

2023-01-19 18:34 UTC, alsala approved these changes

2023-02-07 14:40 UTC, merged