St/evm 480
HorizenOfficial/Sidechains-SDK pull request #686
Opened 2023-01-05 08:22 UTC by saratnt

2023-01-05 15:38 UTC, i-Alex requested changes
looks good!

2023-01-05 15:38 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/chain/SidechainBlockInfo.scala
> +//  }
commented code can be removed

2023-01-05 15:38 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/account/AccountSidechainNodeViewHolder.scala
> +  protected def getNodeView(): AccountNodeView = new AccountNodeView(history(), minimalState(), vault(), memoryPool())
add `override`

2023-01-05 15:38 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/SidechainNodeViewHolder.scala
> +  protected def getNodeView(): SidechainNodeView = new SidechainNodeView(history(), minimalState(), vault(), memoryPool(), applicationState, applicationWallet)
add `override`

2023-01-09 08:15 UTC, saratnt commented on sdk/src/main/scala/com/horizen/chain/SidechainBlockInfo.scala
> +//  }
OK

2023-01-09 14:11 UTC, i-Alex approved these changes

2023-01-09 14:12 UTC, merged