St/mempool size check
HorizenOfficial/Sidechains-SDK pull request #728
Opened 2023-02-09 08:07 UTC by saratnt

2023-02-23 09:04 UTC, saratnt commented on qa/sc_evm_mempool_size.py
> +class SCEvmMempoolSize(AccountChainSetup):
Already solved in PR: https://github.com/HorizenOfficial/Sidechains-SDK/pull/744

2023-02-23 11:26 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/MempoolMap.scala
> +//  private val all: TrieMap[ModifierId, SidechainTypes#SCAT] = TrieMap.empty[ModifierId, SidechainTypes#SCAT]
Done

2023-02-23 11:30 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/MempoolMap.scala
> +    val txOpt: Option[SidechainTypes#SCAT] = executableTxs.get(account).flatMap(map => map.get(nonce).map(txCache(_)))
Done

2023-02-23 11:35 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/MempoolMap.scala
> +      val numOfSlotsOfTxToReplace = if (txToReplace.isDefined){
Done

2023-02-23 13:44 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/MempoolMap.scala
>            val existingTxWithSameNonceId = executableTxsPerAccount(ethTransaction.getNonce)
Done

2023-02-23 13:45 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/MempoolMap.scala
> +      if (getMempoolSizeInSlots > MaxMemPoolSlots) {
Already done in PR: https://github.com/HorizenOfficial/Sidechains-SDK/pull/744

2023-02-23 13:46 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/MempoolMap.scala
> +  private[mempool] def freeMempoolSlots(additionalSlotsToFree: Int = 0): Unit = {
Actually no, it was removed iin PR: https://github.com/HorizenOfficial/Sidechains-SDK/pull/744

2023-02-23 14:00 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +class TxCache {
Done

2023-02-23 14:01 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +    val txInf0 = TxMetaInfo(tx)
Done

2023-02-23 14:54 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +    var previous: Option[TxMetaInfo] = None
Done

2023-02-23 15:02 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +  case class TxMetaInfo(tx: SidechainTypes#SCAT) {
Done

2023-02-23 15:03 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +      if (prev.isEmpty && next.isEmpty){
Done

2023-02-23 16:26 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +  def values: Iterable[SidechainTypes#SCAT] = all.values.map(_.tx)
I have the same doubt but I have tried with a map containing 100000 elements and calling values on it takes around 40 ms. It doesn't seem much

2023-02-23 16:32 UTC, saratnt commented on sdk/src/test/scala/com/horizen/account/mempool/TxCacheTest.scala
> +class TxCacheTest
Done

2023-02-23 16:34 UTC, saratnt commented on sdk/src/test/scala/com/horizen/account/performance/AccountSidechainNodeViewHolderPerfTest.scala
> +      val numOfTxsPerSpammerAccounts = 1
Done

2023-02-24 08:29 UTC, saratnt commented on qa/sc_evm_mempool_size.py
> +    - 1 SC node
I think it is a good idea, remote and local txs may be treated differently and it is worth checking that this is not the case. Done

2023-02-24 08:42 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/MempoolMap.scala
> +            //txCache.add(tx)
Done

2023-02-24 10:51 UTC, alsala requested changes

2023-02-27 09:08 UTC, saratnt commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +Thsi class contains all the transactions accepted in the mempool.
Done

2023-02-27 10:12 UTC, saratnt commented on sdk/src/main/scala/com/horizen/SidechainSettings.scala
> +  require(maxMemPoolSlots > 0, s"Maximum Memory Pool Slots not positive: $maxMemPoolSlots")
Done

2023-02-27 11:09 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/account/mempool/TxCache.scala
> +  def values: Iterable[SidechainTypes#SCAT] = all.values.map(_.tx)
good

2023-02-27 11:14 UTC, i-Alex requested changes
Minor thing left.
Looks good!

2023-02-27 11:48 UTC, alsala approved these changes

2023-02-27 12:03 UTC, i-Alex approved these changes

2023-02-27 12:03 UTC, merged