Check required fields for getBlock... and getTransactionByHash
HorizenOfficial/Sidechains-SDK pull request #750
Opened 2023-02-23 08:01 UTC by akrckn

Delete author in EthereumBlockView - the rest mentioned in [612](https://horizenlabs.atlassian.net/jira/software/c/projects/EVM/boards/12?modal=detail&selectedIssue=EVM-612&assignee=624db49aad6b7e006aa91a3c) are needed and the behavior is the same to what ethereum does.

2023-02-23 14:12 UTC, akrckn commented
Edit: Might be - due to some compiling issues earlier - that I tested with a version before the latest rpc changes - I'll redo the tests and re-assign the Review then!

2023-02-24 13:30 UTC, JcBernack approved these changes

2023-02-24 14:09 UTC, i-Alex requested changes

2023-02-24 14:09 UTC, i-Alex commented on sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumTransactionView.java
> +    @JsonInclude(JsonInclude.Include.NON_NULL)
let's extend one of our Py or Unit tests and check these 3 fields are included only for eip-1559 tx.

2023-02-24 16:54 UTC, i-Alex approved these changes

2023-02-24 16:54 UTC, merged