Utxo package refactoring
HorizenOfficial/Sidechains-SDK pull request #751
Opened 2023-02-27 10:41 UTC by i-skrypnyk

2023-02-27 10:48 UTC, i-skrypnyk commented
It seems that for the short files, like <10-15 lines, idea and git don't want to treat it like renaming and always say it's delete-create changes

2023-02-27 13:09 UTC, i-Alex requested changes
Check the following places:
1. ApplicationNodeViewProvider - seems no one is using -> can be removed at all.
2. NodeViewHelperImpl and TransactionSubmitHelperImpl are Scala class in `Java` part. Do we need them to be written in Scala? If yes move to `Scala` part. If not -> make Java and do the same for Account specific files: `AccountTransactionSubmitHelperImpl`, `AccountNodeViewHelperImpl`
3. Check the package of `MainchainBlockReferenceInfo` and `MainchainBlockReferenceInfoSerializer`. I think we must put it `com.horizen.chain`
4. review `serialization` package. I think we need to call it `json` and inside `json.serializer`  (for Serializers only; `json mapper` can be put into `json` package directly).
5. `com.horizen.account.events` -> `com.horizen.account.state.events` (both scala and java parts)
6.  `com.horizen.account.receipt` -> `com.horizen.account.state.receipt` all except `Bloom` (it can be moved to `account.utils`
7. `account.state` package seems a bit messy, we may split it in several sub packages (to be discussed).
8. `api.http` let's move all routes to a `api.http.route` package. It will help a lot especially in a common package.
9. `RpcIdSerializer` move to account
10. review `com.horizen.utils`: move CswData, FeePaymentsUtils, MempoolMap, UtxoMerkleTreeLeafInfo into `utxo` package.
11. utxo and common package put into a separate subpackages state, wallet, mempool, history; like it is currently structured in `account` model
12. after point (11) move `validation` as a subpackage of `history`

2023-02-28 11:09 UTC, i-skrypnyk commented on sdk/src/test/scala/com/horizen/account/block/AccountBlockTest.scala
> +import com.horizen.utxo.block.SidechainBlock
This is a specific negative check for a wrong version from utxo model

2023-02-28 11:10 UTC, i-Alex commented on sdk/src/test/scala/com/horizen/account/block/AccountBlockTest.scala
> +import com.horizen.utxo.block.SidechainBlock
ok, got it.

2023-02-28 13:41 UTC, i-Alex requested changes
New batch of changes seems good and addressing previous comments.
Beside that a couple of other things:
1. MempoolMap move to mempool package
2. Move SchnorrFunctions into `package com.horizen.cryptolibprovider`
3. couple of places where i see `receipt.EthereumReceipt` -> can be just `EthereumReceipt`
4. SidechainBackup can be moved to `com.horizen.utxo.state`

2023-02-28 14:06 UTC, i-skrypnyk commented
Applied the remaining fixes

2023-02-28 14:11 UTC, i-Alex approved these changes

2023-03-01 08:43 UTC, i-Alex commented on sdk/src/main/scala/com/horizen/utxo/SidechainStateUtxoMerkleTreeProvider.scala
> +import com.horizen.SidechainTypes
will add to the backlog

2023-03-01 08:43 UTC, merged