Block tag additions
HorizenOfficial/Sidechains-SDK pull request #753
Opened 2023-02-28 13:03 UTC by akrckn

add test case to py test, allow no addresses in wallet for pending block, fix block view for pending block after latest changes

2023-03-06 14:30 UTC, JcBernack requested changes

2023-03-09 09:25 UTC, JcBernack commented on qa/sc_evm_rpc_invalid_blocks.py
> +        assert_equal(expected, response["result"], "unexpected response")
"unexpected response" is the error message in case the assert fails:
`def assert_equal(expected, actual, message="")`

2023-03-10 08:32 UTC, i-Alex approved these changes

2023-03-10 09:07 UTC, JcBernack approved these changes

2023-03-10 09:12 UTC, merged