St/mempool base
HorizenOfficial/Sidechains-SDK pull request #754
Opened 2023-02-28 13:38 UTC by saratnt

2023-02-28 14:24 UTC, i-Alex requested changes

2023-02-28 14:24 UTC, i-Alex commented on qa/resources/template.conf
> + accountMempool {
move `allowUnprotectedTxs` from `mempool` to `accountMempool` pacakge.
Fix py tests accordingly.

2023-03-01 07:30 UTC, i-Alex approved these changes

2023-03-01 15:52 UTC, alsala approved these changes

2023-03-01 16:14 UTC, merged