St/SDK 650 - Multisidechain support
HorizenOfficial/Sidechains-SDK pull request #816
Opened 2023-04-24 09:40 UTC by saratnt

2023-05-09 08:55 UTC, paologalligit approved these changes
LGTM, I'd just add a simple test using this new base class that performs few operations on two different sidechains

2023-05-10 09:53 UTC, saratnt commented
I have added a simple test, just to show how to use the framework. This test showed a bug in the framework and I added the fix.

2023-05-17 08:16 UTC, alsala requested changes

2023-05-17 13:58 UTC, saratnt commented on qa/SidechainTestFramework/multi_sc_test_framework.py
> +                connect_sc_nodes(self.sc_nodes[n], n + 1, sc_num=self.sc_num)
Agree. Added magic bytes support.

2023-05-17 14:00 UTC, alsala approved these changes

2024-03-29 09:12 UTC, closed without merging