BootstrappingTool custom message provider injection
HorizenOfficial/Sidechains-SDK pull request #823
Opened 2023-05-09 15:13 UTC by paologalligit

The bootstrapping tool now allow the application layer to customise logic such as injecting custom message processors

2023-05-11 11:55 UTC, MarcoOl94 approved these changes

2023-05-23 16:19 UTC, paolocappelletti requested changes

2023-05-23 16:19 UTC, paolocappelletti commented on examples/mc_sc_workflow_example.md
Step 2 needs an update here (boostraptool jar to be launched)

2023-05-23 16:19 UTC, paolocappelletti commented on examples/utxo/utxoapp_sctool/src/main/java/io/horizen/UTXOSimpleAppBootstrappingTool.java
Let's add a class similar to this one in the tools/sctool module (maybe named "DefaultUTXOBootstrappingTool") and another one for account model.
Can be useful if an app wants just to use the default functionalities without any addition (does not have to definie a whole new full module)

2023-05-29 08:20 UTC, paolocappelletti approved these changes

2023-05-29 08:48 UTC, merged