Sdk-776 MC Block reference delay
HorizenOfficial/Sidechains-SDK pull request #832
Opened 2023-05-24 15:24 UTC by VolodymyrBabaiev

2023-06-15 15:17 UTC, paolocappelletti requested changes

2023-06-30 12:51 UTC, MarcoOl94 requested changes

2023-06-30 13:39 UTC, paolocappelletti requested changes
should be nice to add also at least one test with a delay > 1 (I would try 6)

2023-06-30 13:39 UTC, paolocappelletti commented on sdk/src/main/scala/io/horizen/forge/AbstractForgeMessageBuilder.scala
> +    newHeaderHashes = if(newHeaderHashes.size >= 1) newHeaderHashes.take(newHeaderHashes.size - params.mcBlockRefDelay) else Seq()
newHeaderHashes.size must also be > params.mcBlockRefDelay

2023-07-06 07:15 UTC, VolodymyrBabaiev commented on sdk/src/main/scala/io/horizen/AbstractSidechainApp.scala
> +  protected val maxMcBlockRefDelay = 10
This value was discussed with Paolo and mentioned in design document https://docs.google.com/document/d/1pZDKDffFemEliOBlBGjmoFgL3Eu98bmbQUuNzVM1hhc/edit?usp=sharing

2023-07-06 07:18 UTC, VolodymyrBabaiev commented on sdk/src/main/scala/io/horizen/forge/AbstractForgeMessageBuilder.scala
> +      val maxReferenceDataNumber: Int = Math.min(withdrawalEpochMcBlocksLeft, nextMainchainReferenceDataHeaderHashes.size)
There are 2 limitations of how many blocks we can include - one is MC block delay(we don't want to include some blocks to make delay), the other one is we don't include to one SC block reference of mainchain block form different epochs.

2023-07-06 07:21 UTC, VolodymyrBabaiev commented on examples/utxo/simpleapp/src/main/java/io/horizen/examples/SimpleApp.java
> +        try {
Actually we don't want this information to be passed by command line or set in config. It must set on application layer and be same for every node in the Sidechain. We have to pass it in command line only for testing purpose.

2023-07-11 14:46 UTC, paolocappelletti approved these changes

2023-07-12 09:27 UTC, MarcoOl94 approved these changes

2023-08-31 08:24 UTC, merged