secure enclave http request headers added
HorizenOfficial/Sidechains-SDK pull request #841
Opened 2023-06-06 15:57 UTC by ddrvar

[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-1156?atlOrigin=eyJpIjoiMTg4ODM0OTIwOWM4NDQ3NDg3NWEyMzJiNmVlMGNiN2MiLCJwIjoiaiJ9)

2023-06-08 15:07 UTC, MarcoOl94 requested changes

2023-06-08 15:36 UTC, ddrvar commented on sdk/src/main/scala/io/horizen/api/http/client/SecureEnclaveApiClient.scala
> +        .withEntity(HttpEntity(ContentTypes.`application/json`, ListPublicKeysRequest(SCHNORR).asJson.noSpaces))
Yes, no need for that
I removed it from `HttpEntity` and kept in `headers` list for consistency
Unit tests work

2023-06-08 15:58 UTC, ddrvar commented on sdk/src/main/scala/io/horizen/api/http/client/SecureEnclaveApiClient.scala
> +        .withEntity(HttpEntity(ContentTypes.`application/json`, ListPublicKeysRequest(SCHNORR).asJson.noSpaces))
**Update** - After further debugging I think that actually both have to be kept
The first content-type in headers list adds actual header to the request, and the second one "annotates" entity as `application/json`
This is how the request looks like when I removed content type from Entity - it is annotated as "text/plain", even though there is application/json in the request header
![image](https://github.com/HorizenOfficial/Sidechains-SDK/assets/119593972/3dbdb530-08fc-4383-a350-eb0dd0c343e5)

In the opposite situation when I keep only content type from HttpEntity, no content type header is present in the request, but the entity media type is correctly annotated
![image](https://github.com/HorizenOfficial/Sidechains-SDK/assets/119593972/690c0a1e-a945-4729-b9bb-7bf86cdbe6bc)

2023-06-15 07:57 UTC, MarcoOl94 approved these changes

2023-06-15 08:45 UTC, otoumas approved these changes
LGTM

2023-06-15 08:55 UTC, davehorizen approved these changes

2023-06-19 10:58 UTC, merged