SDK-1144: add cross-chain message validator
HorizenOfficial/Sidechains-SDK pull request #848
Opened 2023-06-09 13:01 UTC by paologalligit

2023-06-12 15:04 UTC, MarcoOl94 requested changes

2023-06-13 07:46 UTC, MarcoOl94 commented on sdk/src/main/java/io/horizen/sc2sc/CrossChainMessageValidator.java
> +    private final static String SENDER_SIDECHAIN_ID_ERROR_MESSAGE = "Sender sidechain id must be 32 bytes long";
I'm usuual to work in this way but It's fine for me to keep like this.

2023-06-14 09:33 UTC, paolocappelletti requested changes

2023-06-14 09:33 UTC, paolocappelletti commented on sdk/src/main/java/io/horizen/sc2sc/CrossChainMessageValidator.java
> +        if (address.length != Constants.SIDECHAIN_ADDRESS_SIZE() && address.length != Constants.ABI_ADDRESS_SIZE()) {
These limits comes from the the type of propositions currently supported in our sidechains, but in the future could be more.
To make it more clear I would remove from Constants ABI_ADDRESS_SIZE  and SIDECHAIN_ADDRESS_SIZE and use in the checks these constants already defined:
io.horizen.account.proposition.AddressProposition.LENGTH
io.horizen.proposition;.PublicKey25519Proposition.KEY_LENGTH

2023-06-14 10:54 UTC, paolocappelletti approved these changes

2023-06-14 11:02 UTC, merged