Sdk 1145 - Payload, addresses and proof format
HorizenOfficial/Sidechains-SDK pull request #849
Opened 2023-06-09 15:18 UTC by paologalligit

2023-06-13 16:36 UTC, MarcoOl94 requested changes

2023-06-14 08:42 UTC, paologalligit commented on sdk/src/main/scala/io/horizen/account/sc2sc/AbstractCrossChainRedeemMessageProcessor.scala
>    private def validateRedeemMsg(ccRedeemMgs: AccountCrossChainRedeemMessage, view: BaseAccountStateView): Unit = {
Because I forgot about it 😅
Gonna add it

2023-06-16 08:22 UTC, MarcoOl94 requested changes

2023-06-16 08:22 UTC, MarcoOl94 commented on sdk/src/main/java/io/horizen/sc2sc/CrossChainRedeemMessageSemanticValidator.java
> +            throw new IllegalArgumentException("Certificate data hash must be 32 bytes long");
Please use constant

2023-06-16 08:22 UTC, MarcoOl94 commented on sdk/src/main/java/io/horizen/sc2sc/CrossChainRedeemMessageSemanticValidator.java
> +            throw new IllegalArgumentException("Sidechain commitment tree root must be 32 bytes long");
Please use constant

2023-06-16 08:59 UTC, MarcoOl94 approved these changes

2023-06-20 13:04 UTC, alsala approved these changes

2023-06-21 07:16 UTC, merged