EON version in node info API
HorizenOfficial/Sidechains-SDK pull request #858
Opened 2023-06-16 13:44 UTC by ddrvar

[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-1207?atlOrigin=eyJpIjoiYWExMDcyNjY4ZGI0NDNlODg1ZWY4ZDFkOGY1ZGI5NzQiLCJwIjoiaiJ9)

EonVersion is binded in `EvmAppModule` and added as an attribute to `AccountSidechainApp`. From there it is forwarded to `SidechainNodeApiRoute`. Default value is null, so for the UTXO model eonVersion won't be returned. Since eonVersion attribute is only added to `AccountSidechainApp` and not to `AbstractSidechainApp`, there is no need to update anything on the UTXO side.

2023-06-19 12:17 UTC, MarcoOl94 requested changes

2023-06-19 12:17 UTC, MarcoOl94 commented on examples/account/evmapp/src/main/java/io/horizen/examples/EvmAppModule.java
> +                .toInstance(eonVersion);
The SDK is a generic framework to build sidechains, here we are adding a reference to a specific project.
I think the best way here is to bind the value to a generic "AppVersion".
So i would rename:

- "EonVersion" -> "AppVersion"
- eonVersion -> appVersion

2023-06-19 12:17 UTC, MarcoOl94 commented on sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala
> +   @Named("EonVersion") eonVersion: String
At this point that we generalized the name, can we use it also inside the UTXO model?

2023-06-20 09:05 UTC, ddrvar commented on examples/account/evmapp/src/main/java/io/horizen/examples/EvmAppModule.java
> +        String eonVersion = "EON VERSION";
Done
Empty string is accepted as binding value

2023-06-20 09:05 UTC, ddrvar commented on sdk/src/main/scala/io/horizen/account/AccountAppModule.scala
> +           @Named("EonVersion") eonVersion: String
Done

2023-06-20 09:05 UTC, ddrvar commented on sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala
> +   @Named("EonVersion") eonVersion: String
Done

2023-06-20 14:16 UTC, MarcoOl94 approved these changes

2023-06-27 13:07 UTC, paolocappelletti approved these changes

2023-06-27 13:13 UTC, merged