SDK-1527: clean old top certificate only if that certificate was alre…
HorizenOfficial/Sidechains-SDK pull request #928
Opened 2023-09-26 14:40 UTC by paologalligit

…ady used as previous cert

## Description
We do not delete the top certificate if it has not yet been used as a previous certificate.

## Jira Ticket
[1527](https://horizenlabs.atlassian.net/browse/SDK-1527)

## Changes
AccountStateMetadataStorageView.scala: introduced a new method that returns an Option with any certificate to be erased

## Breaking Changes
No breaking changes

## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks

2023-10-02 12:45 UTC, MarcoOl94 requested changes

2023-10-02 12:45 UTC, MarcoOl94 commented on sdk/src/main/scala/io/horizen/account/storage/AccountStateMetadataStorageView.scala
> +    val x = calculateKey(Bytes.concat("topQualityCertificate".getBytes(StandardCharsets.UTF_8), Ints.toByteArray(referencedWithdrawalEpoch)))
I think we can remove this

2023-10-02 13:17 UTC, paologalligit commented on sdk/src/main/scala/io/horizen/account/storage/AccountStateMetadataStorageView.scala
> +    val x = calculateKey(Bytes.concat("topQualityCertificate".getBytes(StandardCharsets.UTF_8), Ints.toByteArray(referencedWithdrawalEpoch)))
Oooooops

2023-10-02 13:36 UTC, MarcoOl94 approved these changes

2023-10-09 12:09 UTC, paolocappelletti approved these changes

2023-10-10 10:26 UTC, merged